#ifndef CONSTANTS_HPP
#define CONSTANTS_HPP

#define WINDOW_WIDTH 800
#define WINDOW_HEIGHT  600

#define HEADER_HEIGHT 100
#define HEADER_BORDER_HEIGHT 4
#define HEADER_BORDER_COLOR_R 100
#define HEADER_BORDER_COLOR_G 100
#define HEADER_BORDER_COLOR_B 100
#define HEADER_NAME_SIZE 15
#define HEADER_NAME_COLOR_R 100
#define HEADER_NAME_COLOR_G 100
#define HEADER_NAME_COLOR_B 100
#define HEADER_SCORE_SIZE 15
#define HEADER_SCORE_COLOR_R 100
#define HEADER_SCORE_COLOR_G 100
#define HEADER_SCORE_COLOR_B 100

#define PLAYER_DEFAULT_WIDTH 25
#define PLAYER_DEFAULT_HEIGHT 150

#define BALL_RADIUS 15
#define BALL_COLOR_R 200
#define BALL_COLOR_G 200
#define BALL_COLOR_B 100

#endif // CONSTANTS_HPP
