#ifndef CONSTANTS_HPP
#define CONSTANTS_HPP

#define WINDOW_WIDTH 800
#define WINDOW_HEIGHT  600

#define HEADER_HEIGHT 100
#define HEADER_BORDER_HEIGHT 4
#define HEADER_BORDER_COLOR_R 100
#define HEADER_BORDER_COLOR_G 100
#define HEADER_BORDER_COLOR_B 100
#define HEADER_NAME_SIZE 15
#define HEADER_NAME_COLOR_R 100
#define HEADER_NAME_COLOR_G 100
#define HEADER_NAME_COLOR_B 100
#define HEADER_SCORE_SIZE 15
#define HEADER_SCORE_COLOR_R 100
#define HEADER_SCORE_COLOR_G 100
#define HEADER_SCORE_COLOR_B 100

#define PLAYER_DEFAULT_WIDTH 25
#define PLAYER_DEFAULT_HEIGHT 150
#define PLAYER_DEFAULT_SPEED 0.3 // pixel / ms
#define PLAYER_HORIZONTAL_PADDING 40

#define BALL_RADIUS 15
#define BALL_COLOR_R 200
#define BALL_COLOR_G 200
#define BALL_COLOR_B 100
#define BALL_DEFAULT_SPEED 0.4 // pixel / ms
#define BALL_RANDOM_START_SPEED 0.08  // pixel / ms

#define HEADER_INTRO_SIZE 20
#define HEADER_INTRO_COLOR_R 50
#define HEADER_INTRO_COLOR_G 150
#define HEADER_INTRO_COLOR_B 200
#define HEADER_INTRO_Y 300

#define HEADER_PAUSE_SIZE 20
#define HEADER_PAUSE_COLOR_R 50
#define HEADER_PAUSE_COLOR_G 150
#define HEADER_PAUSE_COLOR_B 50
#define HEADER_PAUSE_Y 300

#define HEADER_WINNER_SIZE 25
#define HEADER_WINNER_COLOR_R 50
#define HEADER_WINNER_COLOR_G 250
#define HEADER_WINNER_COLOR_B 50

#define SOUNDS_ICON_Y 10
#define MUSIC_ICON_Y 50

#define POWER_BLOCK_LIFE_TIME 5
#define POWER_BLOCK_SPAWNING_TIME_MIN 2000 // milliseconds
#define POWER_BLOCK_SPAWNING_TIME_MAX 8000 // milliseconds
#define POWER_BLOCK_WIDTH 50
#define POWER_BLOCK_HEIGHT 50
#define POWER_BLOCK_X_PADDING 100
#define POWER_BLOCK_Y_PADDING 10
#define POWER_BLOCK_MIN_X PLAYER_HORIZONTAL_PADDING + PLAYER_DEFAULT_WIDTH + POWER_BLOCK_X_PADDING
#define POWER_BLOCK_MAX_X WINDOW_WIDTH - POWER_BLOCK_MIN_X - POWER_BLOCK_WIDTH
#define POWER_BLOCK_MIN_Y HEADER_HEIGHT + POWER_BLOCK_Y_PADDING
#define POWER_BLOCK_MAX_Y WINDOW_HEIGHT - POWER_BLOCK_Y_PADDING - POWER_BLOCK_HEIGHT

#define NBR_EFFECTS 5

#endif // CONSTANTS_HPP
