#ifndef CONSTANTS_HPP
#define CONSTANTS_HPP

#define WINDOW_WIDTH 800
#define WINDOW_HEIGHT  600

#define HEADER_HEIGHT 100
#define HEADER_BORDER_HEIGHT 4
#define HEADER_BORDER_COLOR_R 100
#define HEADER_BORDER_COLOR_G 100
#define HEADER_BORDER_COLOR_B 100
#define HEADER_NAME_SIZE 15
#define HEADER_NAME_COLOR_R 100
#define HEADER_NAME_COLOR_G 100
#define HEADER_NAME_COLOR_B 100
#define HEADER_SCORE_SIZE 15
#define HEADER_SCORE_COLOR_R 100
#define HEADER_SCORE_COLOR_G 100
#define HEADER_SCORE_COLOR_B 100

#define PLAYER_DEFAULT_WIDTH 25
#define PLAYER_DEFAULT_HEIGHT 150
#define PLAYER_DEFAULT_SPEED 0.3 // pixel / ms

#define BALL_RADIUS 15
#define BALL_COLOR_R 200
#define BALL_COLOR_G 200
#define BALL_COLOR_B 100
#define BALL_DEFAULT_SPEED 0.4 // pixel / ms
#define BALL_RANDOM_START_SPEED 0.08  // pixel / ms

#define HEADER_INTRO_SIZE 20
#define HEADER_INTRO_COLOR_R 50
#define HEADER_INTRO_COLOR_G 150
#define HEADER_INTRO_COLOR_B 200
#define HEADER_INTRO_Y 300

#define HEADER_PAUSE_SIZE 20
#define HEADER_PAUSE_COLOR_R 50
#define HEADER_PAUSE_COLOR_G 150
#define HEADER_PAUSE_COLOR_B 50
#define HEADER_PAUSE_Y 300

#define HEADER_WINNER_SIZE 25
#define HEADER_WINNER_COLOR_R 50
#define HEADER_WINNER_COLOR_G 250
#define HEADER_WINNER_COLOR_B 50

#define SOUNDS_ICON_Y 10
#define MUSIC_ICON_Y 50

#endif // CONSTANTS_HPP
